
main:  Main.cpp HashStack* GraphPostOrderCursor*
	g++ -o main Main.cpp GraphPostOrderCursor.cpp HashStack.cpp ../Part1/Buffer.cpp ../Part1/NodeIndex.cpp ../Part1/HashSet.cpp ../Part1/Graph.cpp ../Part1/HashQueue.cpp ../Part1/QueueSet.cpp ../Part1/Queue.cpp ../Part1/PairCursor.cpp ../Part2/SCC.cpp